### ISSUE TITLE
关于游戏模式

### ISSUE THREAD

**Issue by 0xMeansHexadecimal** [CodeVS-MC/server#1]
你这个，还是要提高自己的姿势水平！
你不能换了世界，还是想要他给你游戏模式！
因为游戏模式是写在存档里的
你删掉当然大家都默认咯

**Comment by Too-Naive** [comment]
./reset_world.sh

**Comment by 0xMeansHexadecimal** [comment]
[https://github.com/Multiverse/Multiverse-Core/wiki/World-properties#game-mode](url)

给所有人赋予权限
```
mv.bypass.gamemode.*
```
就可以啦

**Comment by Too-Naive** [comment]
交给op就好了 op不嫌麻烦
