### ISSUE TITLE
求取消格雷mod

### ISSUE THREAD

**Issue by Ruanxingzhi** [CodeVS-MC/server#2]
格雷mod已经把游戏难度加到爆了……QAQ

工具耐久变低，一个木头只能合成两个模板，还有一大堆坑爹矿石……

MC应该是一个轻松愉悦的游戏，求取消格雷mod，保留工业2。

**Comment by Too-Naive** [comment]
如果取消格雷mod 那已经发展到一半的人应该怎么办？
第二 纯工业mod已经实验过了 游戏周期太低 导致后期绝大部分服务器时间都是闲置
第三 只是合成冗长了一点 时间花久一点 这并不影响"轻松愉悦"的体验
